/**
 * GENERATED by scripts/fetch-placeholders.mjs — do not edit by hand.
 *
 * Seeds with a downloaded photograph in public/placeholders. Empty means every
 * image is fetched from Picsum at runtime, which is the current, intended
 * behaviour — D10's photographs, unchanged.
 *
 * Run the script to snapshot them locally for speed. It downloads the same
 * Picsum URLs, so the pictures do not change.
 */
export const localPlaceholders = new Set<string>([]);
